default_language_version:
  python: python3.10

exclude: "scripts|src/optimade_launch"

repos:
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
      name: Blacken

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-symlinks
    - id: check-yaml
      name: Check YAML
    - id: check-json
    - id: destroyed-symlinks
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
      name: Fix requirements*.txt
      files: ^requirements.*\.txt$
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.270'
    hooks:
    - id: ruff
      args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    - id: mypy
      name: "MyPy"
      additional_dependencies: ["types-all", "pydantic~=1.10"]
