[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mc_optimade"
authors = [
    {name = "Jusong Yu", email = "jusong.yu@psi.ch"},
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.9"
dynamic = ["version", "description"]

dependencies = [
    "optimade[server]~=0.24.0",
]