---
version: '3'

networks:
  optimade:

volumes:
  # mongo_database:
  #   # name: ${MONGODB_NAME:-mongodb-persist-optimade-01}
  #   name: mongodb-persist-optimade-01
  mongodb-persist-optimade-01:

services:

  mongo:
    restart: always
    image: mongo:4
    volumes:
      - mongodb-persist-optimade-01:/data/db:rw
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 27017:27017
    networks:
      - optimade

  data_inject:
    depends_on:
      mongo:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # JSONL_SOURCE: ${OPTIMADE_JSONL}
      JSONL_SOURCE: "./optimade.jsonl"
    networks:
      - optimade

  optimade:
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
      data_inject:
        condition: service_completed_successfully
    image: ghcr.io/materials-consortia/optimade:0.23.1
    environment:
      MAIN: main
      OPTIMADE_CONFIG_FILE: none
      optimade_insert_test_data: false 
      optimade_validate_api_response: true
      optimade_database_backend: mongodb
      optimade_mongo_uri: mongodb://mongo:27017
      optimade_mongo_database: mc_optimade
      optimade_debug: true
      optimade_structures_collection: structures
      optimade_page_limit: 25
      optimade_page_limit_max: 100
      optimade_base_url: "http://localhost:8081"
      optimade_index_base_url: "http://localhost:8080"
      optimade_provider: "{\"prefix\":\"myorg\",\"name\":\"My Organization\",\"description\":\"Short description for My Organization\",\"homepage\":\"https://example.org\"}"
    ports:
      - ${PUBLISH_PORT:-8081}:5000
    networks:
      - optimade
